### ISSUE TITLE
US4: Golden Path

### ISSUE THREAD

**Issue by LydiaNicolau** [jassellmedina09/Campus_Resource_Locator#13]

**Comment by YanP10** [comment]
User Story:
As a student, I want to search for a building, locate it on the map, and see what's inside.

Scenario:
Scenario: A student wants to find and explore a building on campus.

The student opens the app and sees the campus map.
They enter the building's name or code into the search bar.
The app highlights the building’s location on the map.
The student taps on the building, and a detailed view shows what's inside (departments, facilities, etc.).
The student taps on a specific department or facility for more information, like hours or contact details.
